### ISSUE TITLE
Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'. > More than one file was found with OS independent path 'lib/arm64-v8a/libc++_shared.so'

### ISSUE THREAD

**Issue by agent114** [mafintosh/node-on-android#15]
this error occurs when trying to build APK with out any changes to original file

**Comment by simoarpe** [comment]
Same issue here, the solution I found is in two steps:

* Rename `jniLibs/arm64-v8a/libc++_shared.so` to `jniLibs/arm64-v8a/libc++node_shared.so`
* Change line `401` of `src/main/include/node/common.gypi`
```diff
...
-              'CLANG_CXX_LIBRARY': 'libc++',
+              'CLANG_CXX_LIBRARY': 'libc++node',
...
```
