### ISSUE TITLE
"This app isn't compatible with your phone" - really?

### ISSUE THREAD

**Issue by billiegoose** [mafintosh/node-on-android#21]
What's the minimum system requirements? I'm running Android 7.1.1

**Comment by AlexGustafsson** [comment]
The second line in the README is: 'Make Node.js apps for Android __(Currently only supports ARM64)__'. Are you on an ARM64 architecture?

**Comment by billiegoose** [comment]
Turns out my device *isn't* 64bit. You learn something new every day.
